[project]
name = "rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mujoco>=3.8.1",
    "torch",
    "torchvision",
    "genesis-world>=0.4.7",
    "lerobot[hilserl]>=0.5.1",
    "questionary>=2.1.1",
]

[tool.uv]
exclude-dependencies = [
    "opencv-python-headless",
]
