[project]
name = "rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mujoco>=3.8.1",
    "torch",
    "torchvision",
    "genesis-world>=0.4.7",
    "lerobot>=0.5.1",
    "mediapipe>=0.10.35",
    "orca-core",
]

[tool.uv]
exclude-dependencies = [
    "opencv-python-headless",
    "av",
    "gymnasium",
    "rerun-sdk",
    "torchcodec",
]

[tool.uv.sources]
orca-core = { git = "https://github.com/orcahand/orca_core.git", rev = "main" }
